version: "3.8"

services:
  agent1:
    image: dockeragent:latest
    build:
      context: ./build-context
    restart: unless-stopped
    environment:
      AZP_URL: ${AZP_URL}
      AZP_POOL: ${AZP_POOL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_WORK: agent1
      AZP_AGENT_NAME: ${HOSTNAME}.dockerAgent1
    volumes:
      - type: bind
        source: /azp/agent1
        target: /azp/agent1
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
