version: "3.8"

services:
  agent1:
    image: docker.dl.wago.com/busol/azure-devops-agent:dind
    build:
      context: ./build-context
    restart: unless-stopped
    privileged: true
    environment:
      AZP_URL: ${AZP_URL}
      AZP_POOL: ${AZP_POOL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_WORK: agent1
      AZP_AGENT_NAME: ${HOSTNAME}.dind
      AGENT_ALLOW_RUNASROOT: 0
    command: --once
